In [1]:
from keras.datasets import mnist
from keras.utils import to_categorical
from keras import models
from keras import layers

Using TensorFlow backend.


In [2]:
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()

In [5]:
train_images
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
train_images.shape

(60000, 28, 28)

In [8]:
test_images.shape

(10000, 28, 28)

In [9]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [10]:
network=models.Sequential()
network.add(layers.Dense(512,activation="relu",input_shape=(28*28,)))
network.add(layers.Dense(30,activation="relu"))
network.add(layers.Dense(10,activation="softmax"))

In [11]:
train_images=train_images.reshape((60000,28*28))
test_images=test_images.reshape((10000,28*28))
train_images=train_images.astype('float32')/255
test_images=test_images.astype('float32')/255

In [12]:
train_images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [13]:
train_labels=to_categorical(train_labels)
test_labels=to_categorical(test_labels)

In [14]:
network.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
network.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_2 (Dense)              (None, 30)                15390     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                310       
Total params: 417,620
Trainable params: 417,620
Non-trainable params: 0
_________________________________________________________________


In [15]:
network.fit(train_images,train_labels,epochs=5,batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 10s 159us/step - loss: 0.2781 - accuracy: 0.9187
Epoch 2/5
60000/60000 [==============================] - 9s 154us/step - loss: 0.1027 - accuracy: 0.9699
Epoch 3/5
60000/60000 [==============================] - 9s 148us/step - loss: 0.0668 - accuracy: 0.9796
Epoch 4/5
60000/60000 [==============================] - 9s 150us/step - loss: 0.0463 - accuracy: 0.9858
Epoch 5/5
60000/60000 [==============================] - 9s 148us/step - loss: 0.0350 - accuracy: 0.9889


In [17]:
test_loss,test_acc=network.evaluate(test_images,test_labels)
print("test_acc:",test_acc)
print("test_loss:",test_loss)


10000/10000 [==============================] - 1s 97us/step
test_acc: 0.9797000288963318
test_loss: 0.07028934447395149
